### ISSUE TITLE
[Question] How did you build this?

### ISSUE THREAD

**Issue by gprst** [Keeper-Security/git-ssh-sign#30]
Hi 👋

For educational purpose, I'd like to know if you still had documentation about how git interacts with ssh-keygen to sign commits, unless you reverse-engineered the way git was doing it?

I can't seem to find any documentation about the steps git follows to sign commits with an SSH key, and I am really curious about how you knew what to build 😊

**Comment by EndlessTrax** [comment]
It was mostly reverse engineered by reading the `git` code itself. You can clearly see from the code what git is passing to the signing process and what it expects back. Reading the `ssh-keygen` code got me the rest of the way. It took time, but both codebases are opensource, so it's all there for you to see. Does that answer your question?

**Comment by gprst** [comment]
Yes it does, thank you very much!
